name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: "nixos/nix"

    steps:
    - uses: actions/checkout@v2
    - name: Publish
      run: nix-shell --run 'make setup public release commit'
