name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: "nixos/nix"

    steps:
    - uses: actions/checkout@v2
    - name: Publish
      run: nix-shell shell.nix --run 'make setup public npm-install release setup-git commit'
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GIT_NAME: Max Gonzih via GH Actions
        GIT_EMAIL: gonzih@gmail.com
